# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(858, 590)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.mainLayout = QtWidgets.QHBoxLayout()
        self.mainLayout.setObjectName("mainLayout")
        self.mapWidget = QtWidgets.QWidget(self.centralwidget)
        self.mapWidget.setObjectName("mapWidget")
        self.mainLayout.addWidget(self.mapWidget)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.mainLayout.addItem(spacerItem)
        self.statsLayout = QtWidgets.QVBoxLayout()
        self.statsLayout.setObjectName("statsLayout")
        self.cellNfo = QtWidgets.QWidget(self.centralwidget)
        self.cellNfo.setObjectName("cellNfo")
        self.statsLayout.addWidget(self.cellNfo)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.statsLayout.addItem(spacerItem1)
        self.graphs = QtWidgets.QTabWidget(self.centralwidget)
        self.graphs.setObjectName("graphs")
        self.statsLayout.addWidget(self.graphs)
        self.mainLayout.addLayout(self.statsLayout)
        self.gridLayout.addLayout(self.mainLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 858, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuWindow = QtWidgets.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSavew = QtWidgets.QAction(MainWindow)
        self.actionSavew.setObjectName("actionSavew")
        self.actionImport = QtWidgets.QAction(MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionReset = QtWidgets.QAction(MainWindow)
        self.actionReset.setObjectName("actionReset")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExport_as = QtWidgets.QAction(MainWindow)
        self.actionExport_as.setObjectName("actionExport_as")
        self.actionAdd_cell = QtWidgets.QAction(MainWindow)
        self.actionAdd_cell.setObjectName("actionAdd_cell")
        self.actionAdd_food = QtWidgets.QAction(MainWindow)
        self.actionAdd_food.setObjectName("actionAdd_food")
        self.actionPause = QtWidgets.QAction(MainWindow)
        self.actionPause.setObjectName("actionPause")
        self.actionColors = QtWidgets.QAction(MainWindow)
        self.actionColors.setObjectName("actionColors")
        self.actionStyle = QtWidgets.QAction(MainWindow)
        self.actionStyle.setObjectName("actionStyle")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSavew)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionExport_as)
        self.menuEdit.addAction(self.actionAdd_cell)
        self.menuEdit.addAction(self.actionAdd_food)
        self.menuEdit.addAction(self.actionPause)
        self.menuView.addAction(self.actionColors)
        self.menuView.addAction(self.actionStyle)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.graphs.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuWindow.setTitle(_translate("MainWindow", "Window"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionSavew.setText(_translate("MainWindow", "Save"))
        self.actionImport.setText(_translate("MainWindow", "Open"))
        self.actionReset.setText(_translate("MainWindow", "Reset"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as..."))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionExport_as.setText(_translate("MainWindow", "Export as..."))
        self.actionAdd_cell.setText(_translate("MainWindow", "Add cell"))
        self.actionAdd_food.setText(_translate("MainWindow", "Add food"))
        self.actionPause.setText(_translate("MainWindow", "Pause"))
        self.actionColors.setText(_translate("MainWindow", "Colors"))
        self.actionStyle.setText(_translate("MainWindow", "Style"))
