# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui',
# licensing of 'main_window.ui' applies.
#
# Created: Sat Oct 12 15:21:05 2019
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1500, 1000)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setCursor(QtCore.Qt.WaitCursor)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.mainLayout = QtWidgets.QHBoxLayout()
        self.mainLayout.setObjectName("mainLayout")
        self.mapGView = QtWidgets.QGraphicsView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mapGView.sizePolicy().hasHeightForWidth())
        self.mapGView.setSizePolicy(sizePolicy)
        self.mapGView.setObjectName("mapGView")
        self.mainLayout.addWidget(self.mapGView)
        self.statsLayout = QtWidgets.QVBoxLayout()
        self.statsLayout.setObjectName("statsLayout")
        self.generalStatsLay = QtWidgets.QVBoxLayout()
        self.generalStatsLay.setObjectName("generalStatsLay")
        self.cellStatsLay = QtWidgets.QHBoxLayout()
        self.cellStatsLay.setObjectName("cellStatsLay")
        self.cellPhoto = QtWidgets.QGraphicsView(self.centralwidget)
        self.cellPhoto.setObjectName("cellPhoto")
        self.cellStatsLay.addWidget(self.cellPhoto)
        self.fStatsLay = QtWidgets.QFormLayout()
        self.fStatsLay.setObjectName("fStatsLay")
        self.initFPText = QtWidgets.QLabel(self.centralwidget)
        self.initFPText.setObjectName("initFPText")
        self.fStatsLay.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.initFPText)
        self.initFPLine = QtWidgets.QLineEdit(self.centralwidget)
        self.initFPLine.setReadOnly(True)
        self.initFPLine.setObjectName("initFPLine")
        self.fStatsLay.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.initFPLine)
        self.actFPText = QtWidgets.QLabel(self.centralwidget)
        self.actFPText.setObjectName("actFPText")
        self.fStatsLay.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.actFPText)
        self.actFPLine = QtWidgets.QLineEdit(self.centralwidget)
        self.actFPLine.setReadOnly(True)
        self.actFPLine.setObjectName("actFPLine")
        self.fStatsLay.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.actFPLine)
        self.killsText = QtWidgets.QLabel(self.centralwidget)
        self.killsText.setObjectName("killsText")
        self.fStatsLay.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.killsText)
        self.killsLine = QtWidgets.QLineEdit(self.centralwidget)
        self.killsLine.setReadOnly(True)
        self.killsLine.setObjectName("killsLine")
        self.fStatsLay.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.killsLine)
        self.algaeText = QtWidgets.QLabel(self.centralwidget)
        self.algaeText.setObjectName("algaeText")
        self.fStatsLay.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.algaeText)
        self.algaeLine = QtWidgets.QLineEdit(self.centralwidget)
        self.algaeLine.setReadOnly(True)
        self.algaeLine.setObjectName("algaeLine")
        self.fStatsLay.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.algaeLine)
        self.hungerText = QtWidgets.QLabel(self.centralwidget)
        self.hungerText.setObjectName("hungerText")
        self.fStatsLay.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.hungerText)
        self.hungerLine = QtWidgets.QLineEdit(self.centralwidget)
        self.hungerLine.setReadOnly(True)
        self.hungerLine.setObjectName("hungerLine")
        self.fStatsLay.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.hungerLine)
        self.cellStatsLay.addLayout(self.fStatsLay)
        self.generalStatsLay.addLayout(self.cellStatsLay)
        self.progBarLayout = QtWidgets.QHBoxLayout()
        self.progBarLayout.setObjectName("progBarLayout")
        self.nextGenText = QtWidgets.QLabel(self.centralwidget)
        self.nextGenText.setAlignment(QtCore.Qt.AlignCenter)
        self.nextGenText.setObjectName("nextGenText")
        self.progBarLayout.addWidget(self.nextGenText)
        self.nextGenBar = QtWidgets.QProgressBar(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextGenBar.sizePolicy().hasHeightForWidth())
        self.nextGenBar.setSizePolicy(sizePolicy)
        self.nextGenBar.setProperty("value", 0)
        self.nextGenBar.setObjectName("nextGenBar")
        self.progBarLayout.addWidget(self.nextGenBar)
        self.generalStatsLay.addLayout(self.progBarLayout)
        self.statsLayout.addLayout(self.generalStatsLay)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.statsLayout.addItem(spacerItem)
        self.graphs = QtWidgets.QTabWidget(self.centralwidget)
        self.graphs.setObjectName("graphs")
        self.statsLayout.addWidget(self.graphs)
        self.mainLayout.addLayout(self.statsLayout)
        self.gridLayout.addLayout(self.mainLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1500, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuWindow = QtWidgets.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSavew = QtWidgets.QAction(MainWindow)
        self.actionSavew.setObjectName("actionSavew")
        self.actionImport = QtWidgets.QAction(MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionReset = QtWidgets.QAction(MainWindow)
        self.actionReset.setObjectName("actionReset")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExport_as = QtWidgets.QAction(MainWindow)
        self.actionExport_as.setObjectName("actionExport_as")
        self.actionAdd_cell = QtWidgets.QAction(MainWindow)
        self.actionAdd_cell.setObjectName("actionAdd_cell")
        self.actionAdd_food = QtWidgets.QAction(MainWindow)
        self.actionAdd_food.setObjectName("actionAdd_food")
        self.actionPause = QtWidgets.QAction(MainWindow)
        self.actionPause.setObjectName("actionPause")
        self.actionColors = QtWidgets.QAction(MainWindow)
        self.actionColors.setObjectName("actionColors")
        self.actionStyle = QtWidgets.QAction(MainWindow)
        self.actionStyle.setObjectName("actionStyle")
        self.actionNew_simulation = QtWidgets.QAction(MainWindow)
        self.actionNew_simulation.setObjectName("actionNew_simulation")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionNew_simulation)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSavew)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionExport_as)
        self.menuEdit.addAction(self.actionPause)
        self.menuView.addAction(self.actionColors)
        self.menuView.addAction(self.actionStyle)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.graphs.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.initFPText.setText(QtWidgets.QApplication.translate("MainWindow", "Init Food Pref", None, -1))
        self.actFPText.setText(QtWidgets.QApplication.translate("MainWindow", "Actual Food Pref", None, -1))
        self.killsText.setText(QtWidgets.QApplication.translate("MainWindow", "Kills", None, -1))
        self.algaeText.setText(QtWidgets.QApplication.translate("MainWindow", "Algae eaten", None, -1))
        self.hungerText.setText(QtWidgets.QApplication.translate("MainWindow", "Hunger percentage", None, -1))
        self.nextGenText.setText(QtWidgets.QApplication.translate("MainWindow", "New Gen Loading progress", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.menuEdit.setTitle(QtWidgets.QApplication.translate("MainWindow", "Edit", None, -1))
        self.menuView.setTitle(QtWidgets.QApplication.translate("MainWindow", "View", None, -1))
        self.menuWindow.setTitle(QtWidgets.QApplication.translate("MainWindow", "Window", None, -1))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("MainWindow", "Help", None, -1))
        self.actionSavew.setText(QtWidgets.QApplication.translate("MainWindow", "Save", None, -1))
        self.actionSavew.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+S", None, -1))
        self.actionImport.setText(QtWidgets.QApplication.translate("MainWindow", "Open", None, -1))
        self.actionReset.setText(QtWidgets.QApplication.translate("MainWindow", "Reset", None, -1))
        self.actionSave_as.setText(QtWidgets.QApplication.translate("MainWindow", "Save as...", None, -1))
        self.actionOpen.setText(QtWidgets.QApplication.translate("MainWindow", "Open", None, -1))
        self.actionOpen.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+O", None, -1))
        self.actionExport_as.setText(QtWidgets.QApplication.translate("MainWindow", "Export as...", None, -1))
        self.actionAdd_cell.setText(QtWidgets.QApplication.translate("MainWindow", "Add cell", None, -1))
        self.actionAdd_food.setText(QtWidgets.QApplication.translate("MainWindow", "Add food", None, -1))
        self.actionPause.setText(QtWidgets.QApplication.translate("MainWindow", "Pause", None, -1))
        self.actionPause.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+P", None, -1))
        self.actionColors.setText(QtWidgets.QApplication.translate("MainWindow", "Colors", None, -1))
        self.actionStyle.setText(QtWidgets.QApplication.translate("MainWindow", "Style", None, -1))
        self.actionNew_simulation.setText(QtWidgets.QApplication.translate("MainWindow", "New simulation", None, -1))
        self.actionNew_simulation.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+N", None, -1))

